apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emulator-deploy
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: device-emulator
    spec:
      containers:
      - name: device-emulator
        image: masternz/iodevice-emulator-api:1.2
        ports:
        - containerPort: 8088