apiVersion: v1
kind: Service
metadata:
  name: device-emulator-svc
  labels:
    app: device-emulator
spec:
  type: NodePort
  ports:
  - port: 8088
    nodePort: 30002
    protocol: TCP
  selector:
    app: device-emulator