apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: device-gateway-deploy
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: device-gateway
    spec:
      containers:
      - name: device-gateway
        image: masternz/devicegateway-api:1.1
        env:
        - name: ioDeviceBaseURI
          value: "http://device-emulator-svc:8088"
        ports:
        - containerPort: 8089